version: '3.1'
services:
  scheduler:
    volumes:
      - ..:/usr/local/airflow/host_repo
      - /var/run/docker.sock:/var/run/docker.sock
  webserver:
    volumes:
      - ..:/usr/local/airflow/host_repo
      - /var/run/docker.sock:/var/run/docker.sock
  triggerer:
    volumes:
      - ..:/usr/local/airflow/host_repo
      - /var/run/docker.sock:/var/run/docker.sock