name: Scheduled Automated Retraining

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday
  workflow_dispatch:

jobs:
  retrain_model:
    runs-on: ubuntu-latest

    steps:
      # 1. Authenticate cleanly with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 2. Log into ECR natively to establish pulling permissions
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

     # 3. Pull and run your processing pipeline directly inside the container
      - name: Pull and Execute Retraining Container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "machinery-prod" # Matches your EC2 repository name
          IMAGE_TAG: "latest"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MODEL_NAME: "machinery_failure_anomaly_detector" # Replace with your real model name config
          MODEL_ALIAS: "production"                    # Replace with your real alias config
          BUCKET_NAME: "machinery-mlops-muluneh-2026"
          ALIAS1: "challenger"
        run: |
          # Pull the production image from ECR
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Run in the foreground
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=us-east-1 \
            -e MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI \
            -e MODEL_NAME=$MODEL_NAME \
            -e MODEL_ALIAS=$MODEL_ALIAS \
            -e ALIAS1=$ALIAS1 \
            -e BUCKET_NAME=$BUCKET_NAME \
            -e PYTHONPATH=. \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            sh -c "python src/simulate_labels.py --config-dir /config && python src/evaluate_inference_performance.py --config-dir /config && python src/models/retraining.py --config-dir /config && python src/models/evaluate_models_for_promotion.py --config-dir /config"
